/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c NetworkInterfaceAdapter -a network_adapter.h:network_adapter.cpp -N data/org.freedesktop.SystemManager.xml org.freedesktop.SystemManager.Network
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "network_adapter.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class NetworkInterfaceAdapter
 */

NetworkInterfaceAdapter::NetworkInterfaceAdapter(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

NetworkInterfaceAdapter::~NetworkInterfaceAdapter()
{
    // destructor
}

bool NetworkInterfaceAdapter::connect(const QString &interface)
{
    // handle method call org.freedesktop.SystemManager.Network.connect
    bool out0;
    QMetaObject::invokeMethod(parent(), "connect", Q_RETURN_ARG(bool, out0), Q_ARG(QString, interface));
    return out0;
}

qulonglong NetworkInterfaceAdapter::status(const QString &interface)
{
    // handle method call org.freedesktop.SystemManager.Network.status
    qulonglong out0;
    QMetaObject::invokeMethod(parent(), "status", Q_RETURN_ARG(qulonglong, out0), Q_ARG(QString, interface));
    return out0;
}

