/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c NetworkInterfaceAdapter -a network_adapter.h:network_adapter.cpp -N data/org.freedesktop.SystemManager.xml org.freedesktop.SystemManager.Network
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef NETWORK_ADAPTER_H_1546054274
#define NETWORK_ADAPTER_H_1546054274

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.freedesktop.SystemManager.Network
 */
class NetworkInterfaceAdapter: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.SystemManager.Network")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.SystemManager.Network\">\n"
"    <method name=\"connect\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"interface\"/>\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"status\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"interface\"/>\n"
"      <arg direction=\"out\" type=\"t\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    NetworkInterfaceAdapter(QObject *parent);
    virtual ~NetworkInterfaceAdapter();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool connect(const QString &interface);
    qulonglong status(const QString &interface);
Q_SIGNALS: // SIGNALS
};

#endif
