/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c UserInterfaceAdapter -a user_adapter.h:user_adapter.cpp -N data/org.freedesktop.SystemManager.xml org.freedesktop.SystemManager.User
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef USER_ADAPTER_H_1546054311
#define USER_ADAPTER_H_1546054311

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.freedesktop.SystemManager.User
 */
class UserInterfaceAdapter: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.SystemManager.User")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.SystemManager.User\">\n"
"    <method name=\"auth\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"username\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"password\"/>\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    UserInterfaceAdapter(QObject *parent);
    virtual ~UserInterfaceAdapter();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool auth(const QString &username, const QString &password);
Q_SIGNALS: // SIGNALS
};

#endif
